### ISSUE TITLE
Circular importing in ldc modules

### ISSUE THREAD

**Issue by mattjhill** [ExoCTK/ExoCTK#10]
The use of circular relative imports causes errors in Python 2.7 builds.  lcdfit and lcdplot import each other.

[In ldcfit.py](https://github.com/ExoCTK/ExoCTK/blob/6eb602032d8c889f7e4ef45b6b3c144326e94e0b/ExoCTK/ldc/ldcfit.py#L14-L21)

[In ldcplot.py](https://github.com/ExoCTK/ExoCTK/blob/6eb602032d8c889f7e4ef45b6b3c144326e94e0b/ExoCTK/ldc/ldcplot.py#L15-L22)

The try except statements may seem to fix the issue but what it actually does is import the last installed version of ExoCTK which isn't actually what we want and if you're installing for the first time it won't work.

It looks like the only place the plot library is used is [here](https://github.com/ExoCTK/ExoCTK/blob/6eb602032d8c889f7e4ef45b6b3c144326e94e0b/ExoCTK/ldc/ldcfit.py#L252-L254) which adds some convenience, but I don't think it's asking too much of the user to do something like 

```
>>> from ExoCTK.ldc import lcdfit
>>> from ExoCTK.ldc import ldcplot
>>> coeffs, muz, radius = ldcfit.ldc(teff, logg, FeH, model_grid, profile)
>>> ldfunc  = ldcfit.ld_profile(profile)
>>> ldcplot.ld_plot(coeffs, ldfunc, fig=plot)
```

In the end you only save two lines of code and I'm not sure how we could deal with the importing issue otherwise. So I would say the plotting feature should be removed.

**Comment by hover2pi** [comment]
I removed the ldcfit import from ldcplot (f01efe6) without adding a step for the user. Thanks for the ticket, Matt. Pushed to `ldc_fix` branch and pull request issued!
