### ISSUE TITLE
Docstringz 4 dayz.

### ISSUE THREAD

**Issue by julesfowler** [ExoCTK/ExoCTK#102]
Many of the `contamination_overlap` module is missing its docstrings. 
Since we didn't write it we shouldn't be on the hook for it -- but alas we are...

@hover2pi will do the ones tied into the main module that would be hard to reverse engineer without more familiarity and I'll pick up the ones anyone could come in and do.

**Comment by hover2pi** [comment]
I'm almost done with all of them. Thanks anyway, @julesfowler !
