### ISSUE TITLE
ExoMAST interface to grab orbital parameters/RA,DEC/etc. 

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#108]
Resolve targets via ExoMAST and pull in orbital params

**Comment by catherine-martlin** [comment]
@mfixstsci - do you want to update this with a list of updates that you are working on and that need to be done?

**Comment by hover2pi** [comment]
@mfixstsci Is this done? You implemented the functionality in #212 and #197 so the interface exists, right? I would suggest making separate issues to add the support to each of the other tools.

**Comment by mfixstsci** [comment]
@hover2pi this should be good to go. We should now be getting the RA and DEC via exomast using the infrastructure I wrote into the other PRs.
