### ISSUE TITLE
Contamination overlap tool (expansion).

### ISSUE THREAD

**Issue by julesfowler** [ExoCTK/exoctk#109]
Right now the `contamination_overlap` tool only works on NIRISS SOSS. 
Let's make this generalizable across ALL of JWST...
@exowanderer may have already done/started this.

Jenny edit: 
- [x] Expand Visibility calculator to all JWST instruments by integrating `gtvt`
- [x] Issue https://github.com/ExoCTK/exoctk/issues/221
- [x] Issue https://github.com/ExoCTK/exoctk/issues/144
- [x] Implement `fieldSim.py` and `contamFig.py` into exoctk web
- [x] Test run local version of ExoCTK website to make sure everything works 
- [x] Pull Request

**Comment by jaymedina** [comment]
- [ ] Expanding CO for NIRCam Grism Time Series Mode (for F444W, F322W2) (`gtsFieldSim.py`, `gtsContamFig.py`)
- [ ] Expanding CO for MIRI LRS Mode (`lrsFieldSim.py`, `lrsContamFig.py`)
- [ ] Implementing expansion on the website
