### ISSUE TITLE
Debug `lmfit` in lightcurve_fitting

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#112]
`lmfit` returns starting parameters. Why?

**Comment by hover2pi** [comment]
Or perhaps drop `lmfit` for `starry` (https://github.com/rodluger/starry)

**Comment by exowanderer** [comment]
Just to check that we are storing the output of `res = lmfit.fit(...)` and not calling `lmfit.params` as our output.  I believe that the former (`res.params`)  is the correct format.

Moreover, are you using `lmfit.Minimizer` or `lmfit.Model` to instantiate the fitting?

**Comment by hover2pi** [comment]
Fixed in #176
