### ISSUE TITLE
Write `lightcurve_fitting` subpackage documentation. 

### ISSUE THREAD

**Issue by catherine-martlin** [ExoCTK/exoctk#120]
- [x] Blurb about subpackage on README.
- [x] Example of output of subpackage - image or something demonstrative for users. 
- [x] Read the docs link into README.

Stretch Goal - may migrate to later issue:
- [ ] Notebook Example link to README.

**Comment by hover2pi** [comment]
Perfect. Thanks @catherine-martlin !

**Comment by catherine-martlin** [comment]
I believe that the updates in #159 might complete the third of the checkmarks here.

**Comment by hover2pi** [comment]
Finished checklist with 55646d9
