### ISSUE TITLE
Write updated `groups_integrations` subpackage documentation 

### ISSUE THREAD

**Issue by catherine-martlin** [ExoCTK/exoctk#122]
- [x] Blurb about subpackage on README.
- [x] Example of output of subpackage - image or something demonstrative for users. 
- [x] Read the docs link into README.

Stretch Goal - may migrate to later issue:
- [ ] Notebook Example link to README.

**Comment by catherine-martlin** [comment]
@julesfowler  - does this help with reference to your question on PR #145 ?

**Comment by catherine-martlin** [comment]
Nope! We haven't done this step yet for anything. If you are ready to with your notebook then we could meet to discuss what our format should be for the team.

**Comment by catherine-martlin** [comment]
@julesfowler - not sure if you saw my response! Do you want to meet up and chat about this?

**Comment by julesfowler** [comment]
@catherine-martlin Sorry -- did see this and then spaced. (Lots of PRs flying around recently. 😱)

This is going to be a thing everyone deals with right? Maybe we should discuss at the next ExoCTK meeting?

**Comment by catherine-martlin** [comment]
@julesfowler - It is - would you be willing to guinea-pig a first version talk/example with me? I'd be happy to sit with you and go through it. Then I can present at the meeting with something for others to use as an example on how to take care of this for their packages.

**Comment by julesfowler** [comment]
Oh yeah -- that's fine by me.

**Comment by catherine-martlin** [comment]
I now have an example in my updates to the README in #159 regarding how I'm planning to provide the links to other resources for each package for checkmark 3.
