### ISSUE TITLE
Write updated `limb_darkening` subpackage documentation 

### ISSUE THREAD

**Issue by catherine-martlin** [ExoCTK/exoctk#123]
- [x] Blurb about subpackage on README.
- [x] Example of output of subpackage - image or something demonstrative for users. 
- [x] Read the docs link into README.

Stretch Goal - may migrate to later issue:
- [ ] Notebook Example link to README.

**Comment by hover2pi** [comment]
@catherine-martlin @julesfowler We wanted to move the details of the sub packages out of the top-level README, right? Seems like a number of ways to do it:

1. Separate README in the subdirectory (e.g. `exoctk/exoctk/limb_darkening/README.md`), which will display in Github nicely,
2.  An .rst file in that directory or somewhere else, which can be scooped up by Sphinx,
3. In the`__init__.py` docstring,
4. In the main module docstring,
5. somewhere else?

Which is the least amount of work from a documentation perspective?

**Comment by catherine-martlin** [comment]
Do you mean the modules/functions within `limb_darkening` or when you say sub packages do you mean `limb_darkening` itself? 

I think that we do want to have the package details about these different packages in the top level README. That will be what individuals are responsible for updating and keeping up to date with future versions. From there I will disseminate the updated information to the general ReadtheDocs index.rst page and the ExoCTK website main page/sub package pages. 

The individual .rst files that then create the ReadtheDocs pages for each package will be created by Sphinx out of the docstrings of that code so those do need to be updated to appropriately explain the code.

**Comment by hover2pi** [comment]
Yeah, I mean the sub package itself. For example, the `contam_visibility` tool has about 10 modules in it. We should put docstrings up top in each of them which will be scooped up by Sphinx, but there is no detailed description of that tool as a whole in the sub directory.

My question is, should we have something like a sub package README so the top-level README doesn't get too cluttered beyond install instructions, a general intro, and a blurb about each tool? I guess the notebooks sort of do that though, so... never mind?

Yes, never mind. I think the links to the notebooks from the top-level README will accomplish this. Sorry, I needed to type this out to visualize it!

**Comment by catherine-martlin** [comment]
I believe that the updates in #159 might complete the third of the checkmarks here.
