### ISSUE TITLE
Check ModelGrid flux values

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/ExoCTK#13]
The ModelGrid class seems to be reading in the ATLAS models incorrectly. Check to see if `flux(Teff, logg, FeH, mu)` look similar for ATLAS and ACES grids.

**Comment by hover2pi** [comment]
Nope. For `flux(6000, 5, 0, 1)` the ACES models are ~20 orders of magnitude greater than the ATLAS models. The ACES models seem to be correct though and agree with the LD coefficients from Sing et al. Check the ATLAS flux units!

**Comment by hover2pi** [comment]
Modified `helpers.convert_ATLAS9()` to put models in units of `erg/s/cm**2/cm` (66150d4)

**Comment by exowanderer** [comment]
This is a humorously one sided conversation :)
