### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by gbruno88** [ExoCTK/ExoCTK#14]
The limb darkening coefficients for models in the grid change with the wavelength interval. Instead, if the stellar model is interpolated in the grid (stellar parameter off the grid), the coefficients are the same for every wavelength bin. 

fits_files = '/Users/gbruno/idl/projects/limb_test/phxinten/'    # The same for ATLAS models, but for different (off-grid) stellar parameters
teff, logg, FeH = 5250, 4.0, 0.0
bins = np.arange(1.125, 1.650, 0.00453128*9)
for i in range(1, len(bins)):
        model_grid.customize(Teff_rng=(5000,5400), logg_rng=(3.5,4.5), FeH_rng=(-.5,.5), wave_rng=(bins[i - 1], bins[i]))
        interpolation = lf.ldc(teff, logg, FeH, model_grid, 'linear', mu_min = 0.05, plot=False)

**Comment by hover2pi** [comment]
This is fixed in the `no_filter_class` branch... merge is imminent!
