### ISSUE TITLE
Generate v0.2 release on Github and upload to PYPI/conda

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#147]
Once we verify that the v0.2 release candidate works on the test server (#146 ), we can create an actual release on Github (which will have a DOI) and upload the package to PYPI and conda.

**Comment by hover2pi** [comment]
https://pypi.org/project/exoctk/0.2.1/

**Comment by exowanderer** [comment]
I know that I should know this; but did we set a v0.2 release? If so, what is our DOI?
