### ISSUE TITLE
Mu_min

### ISSUE THREAD

**Issue by gbruno88** [ExoCTK/ExoCTK#15]
The LDC results are closer to Sing's if the PHOENIX models are used, while David used ATLAS models. 
Also, in the plots produced after the fit of the PHOENIX models, the fitted curve does not pass through the modeled points (circles), while it does with the ATLAS models. 
The common cause might be that the LDC deals differently with the minimum mu values in the  PHOENIX and ATLAS models.

**Comment by hover2pi** [comment]
This had to do with the minimum intensity cutoff, not the minimum mu cutoff. I can't point to the exact commit that fixed it, but this is fixed now!
