### ISSUE TITLE
Update C code to work with Python3

### ISSUE THREAD

**Issue by kevin218** [ExoCTK/exoctk#154]
There are 32 light curve model components written in C code to speed up the calculation, but when compiled, the .so files can't be imported using Python3.  We need to update the .c files to work with Python3.

I'm looking for someone to do this in the next 2 weeks.

**Comment by exowanderer** [comment]
I know exactly what needs to be fixed and can work on it next week; but I'm not sure that I could fix *and* test 32 C codes for consistency.  

Specifically, I have a python version checking template for C wrapped python scripts. 

I can make the edits if in one rushed session; but we may have to test it as we use it

**Comment by exowanderer** [comment]
Could you point me at the directory(s) with all of the C codes?

**Comment by kevin218** [comment]
[(https://github.com/kevin218/POET/tree/master/code/lib/models_c)]

There is a routine called `UnitTest.py` that will verify that all of the functions produce correct results (as verified by the Python code).

**Comment by exowanderer** [comment]
Okay. I'll put it on my calendar for Monday. Thank you.

**Comment by exowanderer** [comment]
Mischief Managed: https://github.com/kevin218/POET
