### ISSUE TITLE
Recon for CHIMERA code

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#182]
Contact Mike Line and find out the state of development for CHIMERA. See if there is (or if they are amenable to creating) a stable version in a Github repo that we can write an ExoCTK wrapper for.

**Comment by bourque** [comment]
Note that we already have a repository under the `ExoCTK` organization for this: https://github.com/ExoCTK/chimera, though it looks like the last activity was in December 2016

**Comment by bourque** [comment]
I have sent off an email to Mike asking what the current state of the software is.

**Comment by bourque** [comment]
We have been provided with an updated CHIMERA package by Mike Line.  The next step is to write a wrapper for it, which I will tackle in a separate issue.
