### ISSUE TITLE
Finish `phase_constraint_overlap` tool UI and documentation

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#184]
The guts of this tool were merged with #174 but the UI and documentation need to be finished.

This tool needs:
- [x] a button on the home page
- [ ]  a web interface
- [ ] a jupyter notebook
- [ ] a blurb on the README
- [ ] a test module
- [ ] form validation

**Comment by catherine-martlin** [comment]
Keep updated on #108 for integrating that into a UI system for our website.

**Comment by catherine-martlin** [comment]
See current progress #218

**Comment by catherine-martlin** [comment]
!!! Need to update the equation to include an offset inside the obsDur and winSize portion. The default offset is 0.5 hours. (This has to do with a change in how JWST is going to charge overhead and we want to try to organize the time to be half before and half after on average.)

**Comment by catherine-martlin** [comment]
`obsDur` should be at least twice the transit duration - hardcoded lower limit - make a warning so users know that they should increase.

**Comment by catherine-martlin** [comment]
Option to choose "primary transit" (planet in front of star so phase of 1) or "secondary eclipse" - if eclipse user will have to provide extra info of the eccentricity omega (argument of paraxis) - look into if they are available from ExoMAST.

**Comment by catherine-martlin** [comment]
Remove `t0` from the code - we don't need it.

**Comment by catherine-martlin** [comment]
Also be sure to add in a visual output along with the max/min phase outputs. Can use inputs and create a transit curve with the min phase and one with the max phase to help users visualize their results.

**Comment by catherine-martlin** [comment]
I think we should remove the exomast querying bits and instead have those in the webpages in the same way that the contam and the visibility codes do.

**Comment by bourque** [comment]
I think this is completed now that #313 is merged?
