### ISSUE TITLE
Limb Darkening with Spitzer

### ISSUE THREAD

**Issue by kevin218** [ExoCTK/exoctk#185]
I get an "insufficient wavelength coverage" error when computing LD parameters in Spitzer bandpasses.

Also, vertical dashed line in Bokeh plot is always fixed at 0.05.  It should change based on the minimum mu value.

**Comment by hover2pi** [comment]
Yeah, the default models only go out to 2.5um. I made this issue for model updates. #187 

The mu_min issue is fixed in #186
