### ISSUE TITLE
Error Handling for ExoMAST API data retrieval

### ISSUE THREAD

**Issue by mfixstsci** [ExoCTK/exoctk#201]
When a user enters a target for our tools that request data from the ExoMAST API, if they enter in a bogus name, how should we handle it? Right now the app crashes so it's something we should think about. Some ideas:

1.  Load the same UI with a warning message telling them the target doesn't exist.
2. Load a new UI with some suggestions/troubleshooting options? (Link them to exomast to look there? Suggest another name that the target might go by?)

**Comment by hover2pi** [comment]
I resolved this in #245
