### ISSUE TITLE
Update Read the Docs Content

### ISSUE THREAD

**Issue by catherine-martlin** [ExoCTK/exoctk#205]
- [x] Why isn't automodule working? Is it worth fixing? 
- [x] Update the index page and text information
- [x] Add link to installation instructions in ReadMe

**Comment by bourque** [comment]
I can help take a look at this to see why RTD might be failing.

**Comment by bourque** [comment]
@catherine-martlin See #235 for fixes pertaining to your first TO DO item

**Comment by catherine-martlin** [comment]
See #237 for last few points.
