### ISSUE TITLE
Add autofill for Retrieve Parameters button

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#206]
Replicate the autofill that exomast has when a user is typing in the Retrieve Parameters form. 

We can just ping exomast for all planet names in the db when the app loads and then implement an autofill thingie.

**Comment by mfixstsci** [comment]
Spoke with Susan Mullally about the possibility of retrieving all of the planet identifiers via the api and she said that she has been wanting this for some time now. She said it might be a few months before anyone gets to it but maybe we can leverage `flask_wtf` to do some of this. Here is some weird pseudo code for how you might do this

```python
>>> planet_names=request(all_the_names)
>>> if text_field.changed() and text_field.value() in planet_names:
...     *show available options*
```

**Comment by bourque** [comment]
@mfixstsci Do you know if this is still an open issue, or is this completed now?

**Comment by mfixstsci** [comment]
@bourque I think we should close this. We implemented the form validation after this so I think we can close it. I also added the functionality to catch all of the possible spelling/identifiers names in the planet name field.

**Comment by bourque** [comment]
@mfixstsci Great, thanks!
