### ISSUE TITLE
Look into pyMC3

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#207]
See if pymc3 is a preferable default fitter for the lightcurve_fitting module (rather than lmfit).

**Comment by hover2pi** [comment]
It seems pretty good with the non-gaussian error assumption as a clear advantage. We could go that route but... a bird in the hand and all that. This is definitely not a high priority.

**Comment by exowanderer** [comment]
We don't have to dump the use of lmfit+emcee. We could add PyMC3 as a stretch goal. I am working on a translation interface (i.e. 'wrapper') from LMFIT formatting to PyMC3. I'll let you know when this becomes operational. Then, hopefully, you could stick it into our ExoCTK LCFitter.
