### ISSUE TITLE
Create newsletter for users that want info on updates

### ISSUE THREAD

**Issue by catherine-martlin** [ExoCTK/exoctk#208]
- [x] Figure out how to create a newsletter group. 
- [x] Add blurbs to our github, website, RtDs for users to add themselves. 
- [x] Provide email-able version of signing up

**Comment by catherine-martlin** [comment]
We now have the newsletter email available through listserv - the email address is exoctk-news@maillist.stsci.edu 

I will put together the instructions for people to add themselves and make people from the team do that shortly so we can test it out.

**Comment by exowanderer** [comment]
Assuming that only people inside STScI can add someone to the list: could you add my email to that list, please? jfraine@spacescience.org

If I am wrong, then I look forward to learning how to add myself.

thank you

**Comment by catherine-martlin** [comment]
I was certain to make it so it was open to subscription from outsiders as well! I'll put together the instructions and start posting them shortly. People will be able to subscribe and unsubscribe themselves as they wish regardless of their email affiliation.

**Comment by catherine-martlin** [comment]
Our easiest way to instruct people inside and outside ST to join the mailing list will be the following: 

```Subscribe by email - you are not require to log in to the ListServ interface. 

(1) Send an email from your mailbox to `exoctk-news-subscribe-request@maillist.stsci.edu` 
(2) Subject and body should be blank. If you use an email signature, remove that as well and then send the message.
(3) You will receive a confirmation email - be sure to follow the instructions to ensure you are properly subscribed. 
(4) If you have issues, feel free to contact cmartlin@stsci.edu with "ExoCTK Newsletter" in your subject line.```

Unless we have an ExoCTK email that they should contact instead? 

Also, to unsubscribe - every newsletter will have instructions at the bottom of the email, but we can also post these instructions somewhere: 

```Unsubscribe by email - you are not require to log in to the ListServ interface. 

(1) Send an email from your mailbox to `exoctk-news-signoff-request@maillist.stsci.edu` 
(2) Subject and body should be blank. If you use an email signature, remove that as well and then send the message.
(3) You will receive an email confirming you are unsubscribed. ```

**Comment by catherine-martlin** [comment]
See PR #215 for current progress on the updates to github, our website, and read the docs page.

**Comment by hover2pi** [comment]
#215 is merged. Ok to close this?
