### ISSUE TITLE
Add Eclipse calculations to phase constraint tool 

### ISSUE THREAD

**Issue by catherine-martlin** [ExoCTK/exoctk#211]
Notes regarding this task: "Section 3.2 of the attached book chapter discusses how to compute the time of secondary eclipse.  Setting the period, P = 1, gives us the phase of secondary eclipse.  Eqn 33 is an approximation that works for low eccentricities, but we should implement the full version referenced in the chapter." 

I have the PDF of the chapter available if anyone else wants to see it.

**Comment by exowanderer** [comment]
Is this chapter pdf available in open source format online (i.e. arxiv)? If so, could you provide a link to it.

**Comment by catherine-martlin** [comment]
Good call! 

It's available here: https://arxiv.org/abs/1001.2010v5

**Comment by catherine-martlin** [comment]
See notes on #184 - the info on how to do this is there.

**Comment by bourque** [comment]
Per our discussion during our last meeting, we are setting this to high priority and aiming to get this out for the next release.  I will re-assign to Nestor as soon as I figure out what his GitHub handle is.  Per our notes:

"Enable phase constraint for eclipses, report used eccentricity, and add warning for large eccentricity"
