### ISSUE TITLE
Make time units a dropdown in Groups and Integrations tool

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#228]
Exomast has native time units we want to use in the Groups and Integrations Calculator which may be different than what the user expects. 

Make the time units on the Web form a dropdown with hours/days that defaults to the exomast native units. This necessitates the time units being added as an input in the tool itself along with some simple time conversion snippet.

**Comment by julesfowler** [comment]
@hover2pi @mfixstsci What are the native time units it should default to?

**Comment by hover2pi** [comment]
Fixed in #245
