### ISSUE TITLE
Use AWS to run platon wrapper

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#230]
We currently have a Data Science Innovation Initiative proposal in review that would give us funding for some higher-end machinery on AWS that we could use for running the `platon` wrapper.  Hopefully this gets accepted!

In the meantime, we could try out some minimal working examples on the free tier of AWS.

**Comment by exowanderer** [comment]
I made a PLATON tutorial for Google Colab that I used in a workshop at AUB last November.

Here is a link to the colab: https://colab.research.google.com/github/exowanderer/Exoplanets_ArASIII_Workshop/blob/master/PLATON%20-%20HD209458b%20-%20Example%20Atmospheric%20Retrieval.ipynb

It extends the packaged python notebook from the PLATON GitHub repo. It also installs all of the necessary packages via `!pip` inline. The notebook uses `exomast_api` to access the exo.mast.stsci.edu API and download the spectrum from the MAST archive.

So you can take this tutorial, change the name of the planet being investigated (currently it's HD209458b); then run this code for all the spectra in the MAST archive with PLATON.
