### ISSUE TITLE
Build web app view for atmospheric retrieval tools

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#231]
We should have a webpage that advertises and describes our atmospheric retrieval tools (currently just the `platon` wrapper).

We could use @hover2pi's lightcurve fitting webpage as an example.

**Comment by catherine-martlin** [comment]
This may be related to #239 actually? Just need to have our various bits of information connected across the documentation sources.

**Comment by bourque** [comment]
See #204
