### ISSUE TITLE
Blurb on README for atmospheric retrievals package 

### ISSUE THREAD

**Issue by catherine-martlin** [ExoCTK/exoctk#239]
Please update the README with a short blurb of the `platon wrapper` - or the `atmospheric_retreivals`sub-package if that's more appropriate? Just want to be certain to update our RtDs and our README to match the progress that our website makes.

**Comment by bourque** [comment]
I've taken care of this in #204 with commit https://github.com/ExoCTK/exoctk/pull/204/commits/d10f2c7f0de1e5bcce4b7cf9f9871153b758de35
