### ISSUE TITLE
Mislabelled Phoenix Model

### ISSUE THREAD

**Issue by kevin218** [ExoCTK/exoctk#251]
Should the Phoenix model labelled `M0III 2750 1.5` actually be 3750 K?  Also, is that really the best stellar model for TRAPPIST-1?

**Comment by hover2pi** [comment]
This magically fixed itself. 
<img width="523" alt="Screen Shot 2021-09-01 at 9 25 03 AM" src="https://user-images.githubusercontent.com/34687/131679322-7a3e1dab-c76e-4629-b992-e3c131c1161b.png">
