### ISSUE TITLE
Contam Overlap: "Internal Server Error" issue on website

### ISSUE THREAD

**Issue by jaymedina** [ExoCTK/exoctk#255]
The Contamination Overlap tool is returning an "Internal Server Error" on the website (v0.3) due to a conflict in the Bokeh version (Contamination Overlap code is using Bokeh v 0.13.0, and the server is using v 0.12.5) . Need to fix this by either: Me editing the code w/ the Bokeh version that the server is currently using or by updating the Bokeh version in the server to the latest (v1.0). 

Action plan:
- [x] launch `app_exoctk.py` successfully
- [x] test out Bokeh v1.0 & see what breaks

**Comment by bourque** [comment]
@jaymedina This can be closed now that we switched to using the `exoctk-3.6` `conda` environment (and thus `bokeh>1.0`) on the web server, correct?
