### ISSUE TITLE
ExoCTK Contamination Visibility fails when target is "HAT 6B b"

### ISSUE THREAD

**Issue by jeffchamblee** [ExoCTK/exoctk#257]
ExoCTK Contamination Visibility fails when target is "HAT 6B b". 

Go here: https://exoctk.stsci.edu/contam_visibility
When I put in "HAT 6B b" and click "Resolve Target" and then "Contamination Visibility" I get: "500 internal server error"

Originally discovered in log files of ExoMast as: 

File "/opt/asb/ci/conda/envs/exo-mast/lib/python3.6/site-packages/mast/exo/services/target_visibility.py", line 69, in get
    _, _, _, figure = exoctk.contam_visibility.visibilityPA.checkVisPA(ra, dec, target)

  File "/opt/asb/ci/conda/envs/exo-mast/lib/python3.6/site-packages/exoctk/contam_visibility/visibilityPA.py", line 163, in checkVisPA
    if paNom[i+1] < 10:

Also: 
IndexError: index 366 is out of bounds for axis 0 with size 366

**Comment by mfixstsci** [comment]
@jaymedina Have you seen this behavior before?

**Comment by jaymedina** [comment]
Hi @jeffchamblee , I believe this internal server error is due to the server running a different version of Bokeh from the version used to update the Contam Visibility tool. We're working on a fix for this now, and will update you once it's merged.

**Comment by mfixstsci** [comment]
Thanks for the update @jaymedina!

**Comment by jeffchamblee** [comment]
"HAT 6B b" works now. Looks like this can be closed.

**Comment by jaymedina** [comment]
@jeffchamblee will do - let us know if you have any other issues / suggestions for the visibility calculator!
