### ISSUE TITLE
Running ldc_demo notebook

### ISSUE THREAD

**Issue by exowanderer** [ExoCTK/ExoCTK#26]
In the ldc_demo, there is a line

```
plt.figure()
teff, logg, FeH = 5330., 4.45, 0.06
on_grid = lf.ldc(teff, logg, FeH, model_grid, ['quadratic','4-parameter'], plot=True)
```

I receive an error that says

```python
AttributeError: 'str' object has no attribute 'n_bins'
```

and I did check that file to show that the only mention of `bandpass.n_bins` over the entire package is at that line.  

Because the `bandpass` container is coming from `core.Filters`, I suppose  this was ported out to the `svo_filters` pacakge.

Can we just delete that line?

**Comment by hover2pi** [comment]
No! It'l be fixed when my branch gets merged today!

**Comment by hover2pi** [comment]
All filter stuff has been exported to the separate `svo_filters` module and has been made a dependency. This works fine now.
