### ISSUE TITLE
Improve installation instructions in README.rst

### ISSUE THREAD

**Issue by JeffValenti** [ExoCTK/exoctk#260]
In the main ExoCTK README.rst, add instructions (or a link to documentation) for downloading ExoCTK data and setting the EXOCTK_DATA environment variable.

Fix errors in the Environment Installation section of README.rst:

- File(s) named `environment-<PYTHON_VERSION>.yml` are referenced, but seem not to exist.
- `source activate` is deprecated in favor of `conda activate` in the latest versions of `conda`

**Comment by catherine-martlin** [comment]
Also, add in that you need to be in the `env` directory at the point where you create your environment in conda: 'Next, one can create the exoctk conda environment via the appropriate environment-<PYTHON_VERSION>.yml file'

**Comment by catherine-martlin** [comment]
These issues have been addressed and updates made to the README
