### ISSUE TITLE
Website link to download ExoCTK data yields Internal Server Error

### ISSUE THREAD

**Issue by JeffValenti** [ExoCTK/exoctk#261]
Clicking "ExoCTK Data Downl**ao**d" (note the typo) at the top of the ExoCTK website yields:

> Internal Server Error - The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Perhaps related, selecting "NIRISS.GR700XD.txt" in the "Choose Bandpass" menu on the "Limb Darkening Calculator" page yields the same error.

**Comment by julesfowler** [comment]
I went to do some digging. 
It looks like at some point the function I wrote to returned the zipped data package was replace with just `return`. 

@mfixstsci You can model the function after other data download functions (that should now be removed, now that I think about it) like `fortney`, etc.

**Comment by julesfowler** [comment]
This is closed with #266
