### ISSUE TITLE
Implement bandit, safety, retire.js

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#264]
To better conform to modern security guidelines, we should implement and run (preferably in an automated fashion) security tools such as `bandit`, `safety`, and `retire.js`.  We could also add these dependencies to the `exoctk` `conda` environment (perhaps make separate `dev` `conda` version for this) so that these tools are easy to run when installing and developing on `exoctk`

**Comment by mfixstsci** [comment]
I went ahead and ran `safety` on both of the requirement files `environment-3.5.yml` and `environment-3.6.yml` and there are no current updates necessary. It might be worth looking into adding `saftey` as a hook to the repo https://pyup.io/safety/ci/ 

As for `bandit`, there are a couple or security concerns. I went ahead and ran the software and only wanted the output for "high" risk portions of the code. If anyone else wants to try and run `bandit` to verify that they get the same output, I rant this command:

`bandit -r exoctk/exoctk/ -lll` (the -lll flag report high level risks)

 For version 0.3.0 here is what was reported back:

```
Run started:2019-07-11 15:09:06.748285
Test results:
>> Issue: [B201:flask_debug_true] A Flask app appears to be run with debug=True, which exposes the Werkzeug debugger and allows the execution of arbitrary code.
   Severity: High   Confidence: Medium
   Location: exoctk/exoctk/exoctk_app/app_exoctk.py:987
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b201_flask_debug_true.html
986     port = int(os.environ.get('PORT', 5000))
987     app_exoctk.run(host='0.0.0.0', port=port, debug=True)
--------------------------------------------------
>> Issue: [B605:start_process_with_a_shell] Starting a process with a shell, possible injection detected, security issue.
   Severity: High   Confidence: High
   Location: exoctk/exoctk/exoctk_app/log_exoctk.py:39
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html
38          if os.path.isfile(dbpath) and overwrite:
39              os.system('rm {}'.format(dbpath))
40  
--------------------------------------------------
>> Issue: [B605:start_process_with_a_shell] Starting a process with a shell, possible injection detected, security issue.
   Severity: High   Confidence: High
   Location: exoctk/exoctk/exoctk_app/log_exoctk.py:42
   More Info: https://bandit.readthedocs.io/en/latest/plugins/b605_start_process_with_a_shell.html
41          # Make the new file
42          os.system('touch {}'.format(dbpath))
43  
--------------------------------------------------
Code scanned:
    Total lines of code: 7853
    Total lines skipped (#nosec): 0
Run metrics:
    Total issues (by severity):
        Undefined: 0.0
        Low: 20.0
        Medium: 11.0
        High: 3.0
    Total issues (by confidence):
        Undefined: 0.0
        Low: 1.0
        Medium: 5.0
        High: 28.0
Files skipped (0):
```

Since we are using `os.system` to execute shell commands, there is always the danger of someone trying to inject commands by changing the value of the parsed string. If that isn't a worry, then we can ignore the report and give our reasons to the `exomast` folks. We can also make some small changes to the `os` calls that don't require `os.system`. So instead of this:

```
os.system('touch {}'.format(dbpath))
```

we do this

```
from pathlib import Path
Path(dbpath).touch()
```

I think the code change is better for the long term since it doesn't require much effort on our end but I am open to opinions!

**Comment by bourque** [comment]
@mfix, FYI: PR #268 should take care of integrating `safety` into the `exoctk` repository.

**Comment by mfixstsci** [comment]
Thank @bourque! Should we keep this open until the PR is merged?

**Comment by bourque** [comment]
Sounds good to me

**Comment by bourque** [comment]
@mfixstsci 

> We can also make some small changes to the os calls that don't require os.system. So instead of this:
> 
> os.system('touch {}'.format(dbpath))
> we do this
> 
> from pathlib import Path
> Path(dbpath).touch()
> I think the code change is better for the long term since it doesn't require much effort on our end but I am open to opinions!

I completely agree that this sort of change would be beneficial on multiple levels!  I'd be happy to make those changes, unless you would like to.

**Comment by bourque** [comment]
@mfixstsci I opened a branch (#269) for `bandit` related work.  We can push commits there to address the concerns of `bandit`.

**Comment by bourque** [comment]
As for `retire.js`, I was able to install the software via a Chrome extension, described here: https://github.com/RetireJS/retire.js/tree/master/chrome

However, when trying to run the `exoctk` web app locally to test things, I was unable to get the web app running:

```
(exoctk-3.6) [kramer:exoctk_app] python app_exoctk.py
Indexing models...
No files match /user/bourque/exoctk_data/modelgrid/ATLAS9/* .
Traceback (most recent call last):
  File "app_exoctk.py", line 33, in <module>
    import form_validation as fv
  File "/user/bourque/repositories/exoctk/exoctk/exoctk_app/form_validation.py", line 46, in <module>
    class LimbDarkeningForm(BaseForm):
  File "/user/bourque/repositories/exoctk/exoctk/exoctk_app/form_validation.py", line 51, in LimbDarkeningForm
    teff_rng = mg.Teff_vals.min(), mg.Teff_vals.max()
AttributeError: 'ModelGrid' object has no attribute 'Teff_vals'
```

**Comment by mfixstsci** [comment]
@bourque  hmmmm I thought @jaymedina fixed this one. @jaymedina did that PR with your changes ever get merged?

**Comment by jaymedina** [comment]
I ended up not merging that PR because Joe added the folders (`ACES/` and `ATLAS9/`) that were missing, which prevented us from launching the app (see PR https://github.com/ExoCTK/exoctk/pull/263). However, I don't know exactly where they are.

**Comment by bourque** [comment]
I think we can actually close this now that #268 and #273 is merged.
