### ISSUE TITLE
Groups and Integrations fullwell is busted.

### ISSUE THREAD

**Issue by julesfowler** [ExoCTK/exoctk#284]
Sooo, after I felt comfy that the form was submitting it came time to do a science test and oh boy...

Since at least the 0.3.0 release, the Integrations and Groups Calculator has been spitting out nonsense because ... It is stuck on using a fullwell as a well fraction, and then literally tries to compare that fraction to the decimal percentage. 

Every observation is over saturating because it is more saturated in pixels than ... between .95 and 1. 

I'm really bummed out I didn't catch this with the 0.3.0 release, working on a fix now.

**Comment by julesfowler** [comment]
And, as an also frustrating but lower priority side note, all of my error handling for parameters out of range is gone, to be replaced with an Internal Service Error.

**Comment by julesfowler** [comment]
I have a sloppy fix in for now, also in #283. The next phase is actually understanding the `form_validation` stuff which I don't at present.

**Comment by julesfowler** [comment]
Okay. I'm going to spell out everything that should be done at some point to fix this, and try to figure out what makes sense to do now. 
- [ ] Get the site to produce answers that make sense.
- [ ] Use the `sat_mode` parameter to determine if it's counts or fullwell.
- [ ] Write a catch so that you can't put a counts < a reasonable amount or a fullwell greater than 1.
- [ ] Clean up all of my old error handling in `app_exoctk.py` since it's now happening in `form_validation.py`.
- [ ] Cry a lot.
- [ ] ???

**Comment by kevin218** [comment]
Here are my suggested changes for the G&I calculator:
- [ ] After resolving a target, the returned Observation Time is in units of days but the tab says hours.
- [ ] The calculation for the default Observation Time is wrong.  It should be 3*transit duration.
- [ ] Specify the units (electrons) in the saturation table
- [ ] NIRISS has decreased its saturation limit to ~56k electrons.  Not sure if this is a quick fix or would require sufficient work to postpone this issue until the next release.
- [ ] Relabel the following TA APT column headers:
-  2: Min # of Groups
-  3: Max # of Groups
-  4: Total Duration with Min Groups (seconds)
-  5: Total Duration with Max Groups (seconds)
-  6: Counts Reached with Min Groups (electrons)
-  7: Counts Reached with Max Groups (electrons)
- [ ] Relabel the following SO APT column headers:
-  5: Observation Duration (hours)

**Comment by julesfowler** [comment]
I'm going to call this closed.
