### ISSUE TITLE
Data Download Failing?

### ISSUE THREAD

**Issue by catherine-martlin** [ExoCTK/exoctk#296]
So far we've seen the data download of 12GB fail twice on Chrome (for Kevin around 2.4BG and for Matt) and succeed for Mees on Safari. Not certain if that is the actual problem so Matt is also testing on Safari.

**Comment by catherine-martlin** [comment]
Safari also failed for Matt on today's test.

**Comment by catherine-martlin** [comment]
I was able to download the data today from a Chrome browser - I was on ethernet instead of wifi.

**Comment by mfixstsci** [comment]
Hey All -- Here is some information I obtained from Bryan Hilbert. This might be able to help our data download troubles. This is the data downloader they use for MIRAGE (MIRI data simulator). https://github.com/spacetelescope/mirage/blob/master/mirage/reference_files/downloader.py

**Comment by bourque** [comment]
As we discussed in the last meeting, I think this can be closed now with the addition of the `utils.download_exoctk_data()` function.  We still need to fix the link on the ExoCTK website (#368)
