### ISSUE TITLE
Move reference to EXOCTK_DATA outside of global scope

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#298]
Currently the `EXOCTK_DATA` environment variable is needed upon import of the `exoctk` package since the code that reads it in is in the global scope of `utils.py`.  However, as Jeff Chamblee points out, there are areas of the `exoctk` package that do not require the existence of this environment variable in order to run (e.g. target contamination/visibility).  According to Jeff, it is rather difficult for the ExoMAST application to deal with this environment variable during their build process, so it would be ideal to only call for the `EXOCTK_DATA` variable when it is actually needed, instead of in the global scope. 

Not being familiar with the entire codebase, I am currently not sure how feasible this would be.

**Comment by jaymedina** [comment]
I think it might be useful to see how ExoMAST incorporates the package in their build process. It's true that they don't need `EXOCTK_DATA` at all if the visibility calculator (without contamination) is called in the build process, so maybe just importing that module alone would be enough to solve this issue. @bourque
