### ISSUE TITLE
Contam Overlap: Remove output printing in terminal 

### ISSUE THREAD

**Issue by jaymedina** [ExoCTK/exoctk#302]
The contam overlap tool currently prints the visibilities output when running in a terminal. This clutters the window, so it's best to remove it. 

Note: The print() command is actually in `jwst_gtvt`'s `get_table` function (which the contamination overlap tool then calls) so the modification would be done in there.

**Comment by hover2pi** [comment]
Fixed in #492 by suppressing gtvt output.
