### ISSUE TITLE
Limb Darkening Calculator offline

### ISSUE THREAD

**Issue by guangweifu** [ExoCTK/exoctk#309]
The web version limb darkening calculator seems to be offline. It returns "Internal Server Error".

Also, Data Download failing in google chrome after a few GB as reported by catherine-martlin in issue #296.

@kevin218

**Comment by hover2pi** [comment]
Addressed in #310 .

**Comment by guangweifu** [comment]
I still get "500 internal server error" from the website.

**Comment by hover2pi** [comment]
@guangweifu Oh we haven't deployed it yet. That was a link to a PR which fixes it.

**Comment by guangweifu** [comment]
@hover2pi I installed exoctk and downloaded the exoctk_data file. It can find the fits files but the code crashed at model_grid.customize(). It seems like a path problem about "/internal/data1/exodeploy/exoctk_data/modelgrid/ACES/model_grid_flux.hdf5" ? Any ideas? Thanks!

1056 models loaded from /internal/data1/exodeploy/exoctk_data/modelgrid/ACES/
 Teff  logg ...                          filename                         
------ ---- ... ----------------------------------------------------------
2300.0  3.0 ... lte02300-3.00+0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
2300.0  3.0 ... lte02300-3.00-0.0.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
2300.0  3.0 ... lte02300-3.00-0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
2300.0  3.5 ... lte02300-3.50+0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
2300.0  3.5 ... lte02300-3.50-0.0.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
2300.0  3.5 ... lte02300-3.50-0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
2300.0  4.0 ... lte02300-4.00+0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
2300.0  4.0 ... lte02300-4.00-0.0.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
2300.0  4.0 ... lte02300-4.00-0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
2300.0  4.5 ... lte02300-4.50+0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
 ... ...                                                        ...
7800.0  4.5 ... lte07800-4.50-0.0.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
7800.0  4.5 ... lte07800-4.50-0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
7800.0  5.0 ... lte07800-5.00+0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
7800.0  5.0 ... lte07800-5.00-0.0.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
7800.0  5.0 ... lte07800-5.00-0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
7800.0  5.5 ... lte07800-5.50+0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
7800.0  5.5 ... lte07800-5.50-0.0.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
7800.0  5.5 ... lte07800-5.50-0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
7800.0  6.0 ... lte07800-6.00+0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
7800.0  6.0 ... lte07800-6.00-0.0.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
7800.0  6.0 ... lte07800-6.00-0.5.PHOENIX-ACES-AGSS-COND-SPECINT-2011.fits
Length = 1056 rows
36/1056 spectra in parameter range Teff:  (6000, 6500) , logg:  (5, 5.5) , FeH:  (-0.5, 0.5) , wavelength:  (0, 40)
Loading flux into table...
/home/guangwei/anaconda3/lib/python3.7/site-packages/astropy/table/table.py:919: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  newcol = col[slice_]
Traceback (most recent call last):

  File "<ipython-input-8-64f5d926a699>", line 1, in <module>
    runfile('/home/guangwei/Documents/Work/exoctk_folder/limb_darkening_calc.py', wdir='/home/guangwei/Documents/Work/exoctk_folder')

  File "/home/guangwei/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/guangwei/anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/guangwei/Documents/Work/exoctk_folder/limb_darkening_calc.py", line 23, in <module>
    model_grid.customize(Teff_rng=(6000,6500), logg_rng=(5,5.5), FeH_rng=(-0.5,0.5))

  File "/home/guangwei/Documents/Work/exoctk_folder/exoctk_all/exoctk/modelgrid.py", line 591, in customize
    self.load_flux(reset=True)

  File "/home/guangwei/Documents/Work/exoctk_folder/exoctk_all/exoctk/modelgrid.py", line 502, in load_flux
    f = h5py.File(self.flux_file, "w")

  File "/home/guangwei/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)

  File "/home/guangwei/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 176, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)

  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py/h5f.pyx", line 105, in h5py.h5f.create

OSError: Unable to create file (unable to open file: name = '/internal/data1/exodeploy/exoctk_data/modelgrid/ACES/model_grid_flux.hdf5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 242)

**Comment by hover2pi** [comment]
@guangweifu Ok, the LD tool is back online! Give it a whirl and post another issue if you run into any other problems!
