### ISSUE TITLE
Add NIRSpec support in LDC

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#312]
@gbruno88 points out that NIRSpec filters are missing from the LDC because they are missing from the SVO Filter Profile Service.

Add them manually to the list of filters in the `svo_filters` package the way NIRISS.GR700XD was added. Then pull the new version of `svo_filters` into the `exoctk` production server.

**Comment by hover2pi** [comment]
@gbruno88 [Here](https://jwst-docs.stsci.edu/near-infrared-spectrograph/nirspec-instrumentation/nirspec-dispersers-and-filters#NIRSpecDispersersandFilters-NIRSpecDispersersNIRSpecdispersers) is the list of nine disperser+filter combinations available for NIRSpec. My plan was to find the transmission curves for each combination, multiply them, and then supply them in the LDC dropdown list as NIRSpec_G140M_F070LP, NIRSpec_G140M_F100LP, NIRSpec_G235M_F170LP, etc. Is that what you are looking for?

**Comment by gbruno88** [comment]
Yes, that sounds great!

**Comment by hover2pi** [comment]
Completed in #499
