### ISSUE TITLE
make PYSIAF a dependency for ExoCTK

### ISSUE THREAD

**Issue by jaymedina** [ExoCTK/exoctk#322]

**Comment by bourque** [comment]
@jaymedina Is the task here to simply add `pysiaf` to our `exoctk` environment files? or was there something else to this?

**Comment by jaymedina** [comment]
1. add pySIAF
2. replace my hard-coded parameters with the pySIAF parameters 
@bourque

**Comment by bourque** [comment]
👍 Ok, let me know if you need any help on the environment side of things.
