### ISSUE TITLE
Incorrect observation duration in Phase Constraint Overlap

### ISSUE THREAD

**Issue by kevin218** [ExoCTK/exoctk#337]
Line 72 should read `obsDur = np.max((6, 3*transitDur+1))`

**Comment by mfixstsci** [comment]
On it

**Comment by mfixstsci** [comment]
@kevin218 just made the change: #338

**Comment by catherine-martlin** [comment]
Reviewed and merged!

**Comment by kevin218** [comment]
The website still lists the transit duration as 6 hours.  Can we update this asap?
