### ISSUE TITLE
Fix target selection for PandExo

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#345]
Currently PandExo does not correctly handle fields that cannot be auto-populated, leading to errors when a user hits submit.

**Comment by nespinoza** [comment]
This has been resolved in the latest PR to PandExo: https://github.com/natashabatalha/PandExo/pull/37. We need to pull those changes to our "local" PandExo repo to solve this.

**Comment by nespinoza** [comment]
Solved in latest online PandExo version!
