### ISSUE TITLE
ExoCTK (Webapp) Contamination & Visibility Tool crashes if no Target Name is given

### ISSUE THREAD

**Issue by nespinoza** [ExoCTK/exoctk#355]
Hi team,

 Jennifer Patience (ASU) contacted us via the HelpDesk to let us know that there is a bug in the ExoCTK web application in the Contamination & Visibility Tool. The bug is that if you input an RA and DEC, but don't input anything on the "Target Name (optional)" field, the web application crashes with an "Internal Server Error". Luckily, for users a hack/solution is immediate, and for us the fix should be relatively simple:

  **(a) For users**: a quick hack is to simply input a fake name under the "Target Name (optional)" field (e.g. "my star"). Then, the tool works just fine as expected.

 **(b) For us**: I checked the code and this might arise because the form reads "nothing" as a `None`, and that makes the validation of the form to crash. The fix for this should be relatively simple enough to do for the web app experts.

I'm assigning @mfixstsci, @jaymedina, @bourque and myself who have expertise with the web app (based on recent commits) to this. I can commit to take a look at this before April, but if any of you have 10 minutes to spare to fix this, please do. I would most likely take longer than that :-).

Thanks!

- Néstor

**Comment by jaymedina** [comment]
@nespinoza thanks for the notice! I just tested a quick fix for this that seems to be working. I will go ahead and make a PR now.
