### ISSUE TITLE
`app_exoctk.py` : `ImportError: cannot import name 'url_encode'`

### ISSUE THREAD

**Issue by jaymedina** [ExoCTK/exoctk#358]
Hi all, I’m working with a fresh install of exoctk and ran into an obstacle that we should address: 

When trying to run the web app, I received the following error `ImportError: cannot import name 'url_encode'`

<img width="854" alt="image" src="https://user-images.githubusercontent.com/32107699/77014399-8e0d0080-6948-11ea-9167-794d8b47cc34.png">

After a quick dig for a solution, it looks like the issue was addressed in Issue https://github.com/pallets/flask/issues/3481

Apparently Flask recently (this February) updated its `werkzeug` dependency to `werkzeug==1.0` which is where the problem arises. It looks like a temporary solution involves reverting to `werkzeug==0.16.1`

I can make a pull request to fix this, but more importantly I'm wondering what should be our protocol to avoid situations like these after a fresh install? Should we be explicit with the version # for all of our dependencies? 

@nespinoza @bourque @mfixstsci

**Comment by bourque** [comment]
I think the best way to catch things like this is to write (more) unit tests that gets executed during the Travis build.  Currently our environment files do indeed install explicit versions of packages, but only ones that we import directly somewhere within the `exoctk` package.  But since `werkeug` is a dependency of a dependency (in this case `flask_wtf`), I'm not sure how best to avoid this -- at the end of the day it is the fault of `flask_wtf` for packaging their code with a broken dependency 🤷‍♂

**Comment by nespinoza** [comment]
Hi all,

 Thanks @jaymedina for bringing this to an issue --- while doing my fresh install I ran across the same issue and totally forgot to report it! So --- if we force the installation of `werkzeug==0.16.1` prior to installing `flask`, would `flask` update the version or keep that one? Alternatively, a quick workaround would just to add a line or two to downgrade `werkzeug` after installing `flask` --- is this what you had in mind @jaymedina?

**Comment by mfixstsci** [comment]
@bourque thats what I was going to suggest. IIRC the python package manager should catch those dependencies, but I could be wrong.

**Comment by jaymedina** [comment]
@nespinoza what I did on my local environment was install `werkzeug==0.16.1` by itself first, then installed `flask` without specifying a version. I had concerns that `flask` would override my `werkzeug==0.16.1` with the newest version, but it seemed to work.

So it might be enough to just add a line of code somewhere in the `setup.py` and environment `.yml` files to explicitly download `werkzeug==0.16.1`

**Comment by nespinoza** [comment]
Hey @jaymedina --- that sounds good to me! If you could push that, that would be great --- let's test it on a fresh install tough just to be sure it works! Thanks!

N.
