### ISSUE TITLE
Drop conda envrionment for Python 3.5?

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#366]
ExoCTK currently supports Python versions `3.5`, `3.6`, and `3.7` through the provided [`conda` environments](https://github.com/ExoCTK/exoctk/tree/master/env).  I propose that we drop support for python `3.5`, as it is not widely used in the python community.  Additionally, per the upcoming Tier 2 standards for STScI supported INS JWST, we will require these tools to use `python>=3.6` anyways.

Any opinions on this? @nespinoza? @hover2pi?

**Comment by nespinoza** [comment]
Hey @bourque. Sorry for taking so long to answer to this. I agree with you --- let's drop 3.5.
