### ISSUE TITLE
Update "ExoCTK Data Download" link on homepage

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#368]
The "ExoCTK Data Download" link on the ExoCTK homepage still attempts to download the data package, but this likely breaks for most users.  Now that we have the `utils.download_exoctk_data()` function, and a public box folder with the data, we can update this link to a page with instructions on how to obtain the data manually.

**Comment by exowanderer** [comment]
Hello @catherine-martlin, @mfixstsci, and @bourque, 

I read over your issue page updates about this (here and on #296). I had similar problems in January and February *(2020). Your updates in May (2020) seem to be promising. I used multiple operating systems and multiple web-browsers: OSX, Windows, Linux + FireFox, Safari, and Chrome; all had the same issue: after a few GB, the download would fail.

My question here is: does the "ExoCTK Data Download" button on our website work now?

Did we change the behaviour of that button to activate the `utils.download_exoctk_data()` call inside the ExoCTK package? Or are we assuming most users will find their way to the `download_exoctk_data` after installing ExoCTK on their systems?

A second question would be: if the "ExoCTK Data Download" has not been updated, then is it still 'broken' and should we keep it at all?

Note: I'm testing our website's download button now. I will report the success/failure in a few hours ("yay for slow internet!")

**Comment by bourque** [comment]
Hey Jonathan!  Hope all is well with you and the family over there!

Yeah, the download button currently is still broken, with the 'failing after a few GB' problem.

I have a (work in progress) PR to address change the behavior of this button (#369).  This PR will update the install instructions in the README to guide users to the `download_exoctk_data()` function, and the download button on the ExoCTK website will just redirect the user to these instructions.

I'm open to other suggestions of how to make this process easier/different for users if you or the rest of the team have any! Feel free to comment on #369.  If #369 is fine as it is, i'm hoping that it can be merged soon and made available in our upcoming release. 

CCing @nespinoza here, as the reviewer of #369.

**Comment by nespinoza** [comment]
Hey Jonathan! Adding to @bourque's comments, our plan for the release following the next one (i.e., our [future-future release, v1.2](https://github.com/orgs/ExoCTK/projects/12)) is to download data as needed by the users on a task-to-task basis. That would solve most (if not all) of our problems related to this.
