### ISSUE TITLE
Limb-darkening table not being returned in web-service for more than >20 channels

### ISSUE THREAD

**Issue by nespinoza** [ExoCTK/exoctk#372]
Hi everyone,

 Turns out that if you try to use the [limb-darkening web-service](https://exoctk.stsci.edu/limb_darkening) for more than about 20 channels, the returned table (and downloaded file) only has the limb-darkening of up to 20 channels, at least for `NIRISS.GR700XD.1` (haven't tried the other ones, but the problem seems to be general). The web results look like so when I tried to obtain the LD coefficients for HAT-P-1 over 100 channels:

![Screen Shot 2020-05-21 at 4 41 24 PM](https://user-images.githubusercontent.com/2046682/82604215-f4e5aa80-9b81-11ea-8554-a88475ce93a6.png)

 So, not all results are shown as there are these dots between the first ~10 wavelength channels and the last 10. When you download the file by clicking on "Download coefficient Tables", you get a file which has the following in it:

![Screen Shot 2020-05-21 at 4 42 56 PM](https://user-images.githubusercontent.com/2046682/82604324-25c5df80-9b82-11ea-8c83-005f31bbf850.png)

 i.e., the same table as the web-version (with the dots and not the data) is returned.

 Judging from the plots in the webpage, it seems the results _are_ being computed in the back-end code, so this is very likely a front-end problem.

 I'm assigning @hover2pi and myself to this. I'm going to take a look at this in the next few days and try to get it fixed, but if anyone has any quick idea of what is going on, that would be great :-).

Néstor

**Comment by hover2pi** [comment]
Fixed in #381 . This was happening because of the way `astropy.table` truncates a long and/or wide table. It's fixed with the arguments `max_lines=-1` and `max_width=-1`.
