### ISSUE TITLE
Missing Info in Downloaded Limb Darkening Table

### ISSUE THREAD

**Issue by kevin218** [ExoCTK/exoctk#374]
Upon clicking "Download Coefficient Tables" I get the attached result.  There is no description of wavelength (min, eff, and max) as shown in the online table.

Also, there is a typo in the default file name: ExoXTK_results.txt

[WASP74-LD.txt](https://github.com/ExoCTK/exoctk/files/4732731/WASP74-LD.txt)

**Comment by hover2pi** [comment]
Oh yeah, that's just `astropy` truncating the table. Those are easy fixes. Thanks Kevin!
