### ISSUE TITLE
New HST Calculation

### ISSUE THREAD

**Issue by exonik** [ExoCTK/exoctk#376]
Dear Colleagues,

Pandexo WFC3 gives an error when running with typical exoplanet parameters, e.g. WASP-123b. Below is an example of a set up which would run, but an error is produced when I click on the visualization icon after the run. I noticed that the error disappears when I switch from 'Planet model: Constant' value to specific parameters, e.g. 'Teq=1775, Eq chem., Nothing and 0.5 MJ', which could be the reason for the issue.

Configuration that produces the error:

Name: WASP-123
 
Star/Planet Properties: User Defined
Mag for host: 9
Color cor.: 9.4 or blank
Stellar Teff:: 5740
Pl. rad.: 1.3
St. rad.: 1.3
Orb incl.: 83.0
Semi-maj. axis: 9
Orb. Ecc.: 0
Long of periast.: 180 or 0 or blank
 
Planet model: Constant value
 
Observation Parameters:
N HST orbs: 5
N transits/ecl.: 1
N channels: 12
Obs. Start window: 20 min
Use the first orbit: False
Target fluence: 30000
 
Instrument: WFC3
Instrument Parameters:
141
GRISM256
Optimal
Optimal
Round trip
30 (Small/Medium Programs)
 
Ramp Effects: off

**Comment by JeffValenti** [comment]
@exonik - In the "Planet Model" section of the form in the "Select Planet Model Units" menu, did you select "(Rp/R*)^2 (primary)" or "Fp/F* (secondary/phase curve)"?  Is an error message printed?

**Comment by exonik** [comment]
@JeffValenti - Adding the "(Rp/R*)^2 (primary)" or "Fp/F* (secondary/phase curve)" solved the problem. Thanks! I somehow missed the units.

**Comment by JeffValenti** [comment]
Happy to have a simple issue to solve!
