### ISSUE TITLE
Check for existence of appropriate EXOCTK_DATA directories when necessary

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#386]
Currently, the `EXOCTK_DATA` environment variable is checked upon import of `exoctk` and errors are thrown if the variable doesn't exist or doesn't contain the appropriate sub-directories (see [utils.py](https://github.com/ExoCTK/exoctk/blob/master/exoctk/utils.py#L30)). 

This is not ideal for users and/or dependent projects (such as ExoMAST) who only care about invoking a small part of the `exoctk` code (for example, ExoMAST only uses `exoctk.contam_visibility.visibilityPA.using_gtvt`).  Regardless of what code is being used, they have to deal with all of these sub-directories.

The solution would be to go into the code and only insist that the user have the appropriate `EXOCTK_DATA` directories when necessary.

**Comment by bourque** [comment]
Tagging @falkben so that he can keep track of this issue for ExoMAST

**Comment by nespinoza** [comment]
Hi folks (tagging @falkben) --- this is in our plans for v.1.2 of ExoCTK (i.e., the release after the next release). We'll get it sorted out, but in the meantime, we advise users to install/download the whole dataset before using ExoCTK. We understand this is not ideal, but we'll solve it eventually in the next few months (we have other higher priority issues with which we need to deal with first!).

N.

**Comment by catherine-martlin** [comment]
For reference, from discussion today: https://github.com/ExoCTK/exoctk/blob/master/exoctk/contam_visibility/field_simulator.py

**Comment by bourque** [comment]
Completed via #488
