### ISSUE TITLE
setup.py pinned versions cause challenges on python >= 3.8

### ISSUE THREAD

**Issue by falkben** [ExoCTK/exoctk#387]
Exoctk has several libraries pinned that are not easily installable under python 3.8 or conflict with some of our other libraries (specifically scipy & pyyaml)  https://github.com/ExoCTK/exoctk/blob/v1.0.0/setup.py#L33

I haven't yet looked through to have an idea of why these dependencies were pinned in such a way.  

scipy is probably the thing we need updated the most as versions < 1.3 don't install easily on python 3.8 (requires compiling, which fails on my mac due to fortran issues I haven't tried to debug).

Conda's oldest version which supports 3.8 is 1.3.1.  But scipy is currently at 1.5.2 and ideally we'd just use that.

Our requirement for python 3.8 comes from fastapi, which runs best on recent versions of python, though we could use 3.7 if we had to, python 3.9 is just about to come out so I think 3.8 is the correct choice for us at this point.

Currently we are getting install issues with exoctk by pinning the most recent scipy version. However, I'm curious whether that will cause any known issues or, ideally, whether we can get exoctk to pin a scipy version >= 1.3.1?

Thanks!

**Comment by nespinoza** [comment]
I think jumping scipy up to >= 1.3.1 shouldn't be too much trouble (we need to check this however). Will discuss it internally in our next team meeting (next week) and let you folks know!
