### ISSUE TITLE
Mu cutoff on the online limb-darkening calculator should be on the "model" and not the "star"

### ISSUE THREAD

**Issue by nespinoza** [ExoCTK/exoctk#407]
Hi folks,

 On today's ExoCTK team meeting, @JeffValenti suggested that the mu cutoff value that is asked to the user on the online tool shouldn't be a stellar property, but rather part of the model (i.e., be on the same spot where the limb-darkening law is defined). A picture is worth more than my previous 308 characters:

<img width="1039" alt="Screen Shot 2020-09-01 at 5 18 06 PM" src="https://user-images.githubusercontent.com/2046682/91907180-5cc68980-ec77-11ea-8aa4-65f9f9b13e80.png">

 I'm assigning @hover2pi to this for efficiency, and also assigning low priority to this (set to v1.2 of ExoCTK).

N.

**Comment by hover2pi** [comment]
Fixed in #409
