### ISSUE TITLE
HDF5 files have hard coded directory structures

### ISSUE THREAD

**Issue by exowanderer** [ExoCTK/ExoCTK#41]
I was trying to reproduce some of the figures in AWESim_SOSS, but they rely on `model_grid.p` and `model_grid_flux.hdf5`, which are built into ExoCTK.core.

These files include specific pathnames that request write access to `/user/jfilippazzo/models/aces/default/`.

We should to make this more malleable. But it seems in-grown in a way that I can't fix easily.

**Comment by exowanderer** [comment]
My only work around today was to make a fake directory on my local machine called `/user/jfilippazzo/models/aces/default/` and then symbolically link it to my local ACES model files

**Comment by hover2pi** [comment]
No longer applicable with the new ModelGrid class.
