### ISSUE TITLE
NIRISS to pySIAF in Contamination Overlap

### ISSUE THREAD

**Issue by nespinoza** [ExoCTK/exoctk#434]
Currently, the NIRISS SOSS algorithm for the Contamination Overlap, which was developed by the University of Montreal uses their own Science Instrument Aperture Files (SIAF), while the NIRCam and MIRI algorithms were developed at STScI and use the most up-to-date Science Instrument Aperture Files (SIAF), which are called from STScI's pySIAF package. We need to find out eventually if we can pass SOSS to pySIAF (or if there are plans to do that from STScI's side).

@jaymedina --- I might be able to find figure this out. This will become handy once commissioning data comes --- not critical now, but will be after comissioning (for Cycle 2).

**Comment by jaymedina** [comment]
Definitely. Once the multiprocessing is implemented, this should be as easy as copy-pasting the script over to the `sossFieldSim()` function. This also applies for expanding the tool to any other instrument/mode, now that the code has been generalized with `pySIAF`. @nespinoza

**Comment by hover2pi** [comment]
Resolved in #492
