### ISSUE TITLE
IndexError out of bounds in exoctk.contam_visibility.visibilityPA.using_gtvt

### ISSUE THREAD

**Issue by falkben** [ExoCTK/exoctk#436]
I'm seeing that under certain circumstances (ra/dec) we are getting an out of bounds error in the `contam_visibility.using_gtvt` function at this line of code: https://github.com/ExoCTK/exoctk/blob/master/exoctk/contam_visibility/visibilityPA.py#L408

It looks like when we go to retrieve values from badPA there's an index out of bounds error.
Does it makes sense that `badPAs` would ever be empty?

Here's the ra/dec that we're using.

```python
exoctk.contam_visibility.visibilityPA.using_gtvt(ra, dec, instrument, targetName="Target", output="bokeh")
```

where our inputs are

```
ra = '88.5897756488149'
dec = '-64.1297956126618'
instrument = 'NIRISS'
```

and the error is

```
exoctk/contam_visibility/visibilityPA.py", line 400, in using_gtvt
    grouped_badPAs = [[badPAs[0]]]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by nespinoza** [comment]
Hi @falkben --- thanks for finding this! 

 We'll have a look together with @jaymedina, who is the tool champion for this. I think `badPAs` will only be an empty array if the target is always observable, which is the case for the Continuous Viewing Zone (CVZ; https://jwst-docs.stsci.edu/jwst-observatory-hardware/jwst-observatory-coordinate-system-and-field-of-regard). The RA of this target is ~6 hours and declination is -64 degrees, which actually falls in the CVZ (see Figure 6 in the article) --- so this seems to be indeed the problem.  I would like, however, for @jaymedina to confirm this is the case. If it is, then this needs some little tweaks to solve this edge case, but should be relatively straightforward (just a couple of if statements in this and other functions that assume `badPAs` is not empty).

 Thanks again for submitting this! Will let you know how this gets solved.

Néstor

**Comment by jaymedina** [comment]
Hi @falkben , thanks for opening this issue. @nespinoza is right, the `badPAs` array would be empty in cases where the target is visible 100% of the time, which seems to be the case with this target. I've opened a PR with a fix that accounts for cases like this ( PR https://github.com/ExoCTK/exoctk/pull/438) , and running the visibility calculator in this branch gives me the following output: 

![image](https://user-images.githubusercontent.com/32107699/97668328-12377280-1a58-11eb-99c2-409ba1074dfe.png)

It looks like there is always at least 1 position angle in which this target can be viewed in (thus, no "bad PAs"), which is consistent with what Nestor mentioned about this target landing in the CVZ. 

We will update this ticket when the PR gets merged and you can run the visibility tool as normal. Thanks for catching this bug!
