### ISSUE TITLE
Do a sweep of the repo for missing docstrings

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#446]
As part of the [INS JWST Community Software Tier 2 standards](https://github.com/spacetelescope/ins-jwst-community-software#contents), we need to ensure our software contains docstrings for all modules, classes, and functions.

**Comment by nespinoza** [comment]
Hi folks,

 Let's use this same issue to write a checklist for this. Once everything is checked, we can call this done! Mark below if you have checked/updated the modules on the code below such that all the classes/functions have docstrings:

- [ ] Groups & Integrations (to be checked by @catherine-martlin and/or @bourque).
- [ ] Contamination overlap (to be checked by @hover2pi and/or @jaymedina).
- [ ] Forward modelling (to be checked by @nespinoza).
- [ ] Limb-darkening calculator (to be checked by @hover2pi).
- [ ] Phase-constraint calculator (to be checked by @nespinoza).
- [ ] Higher level modules (i.e., utils, web app, etc. --- to be checked by @nespinoza, @hover2pi and/or @bourque)

**Comment by bourque** [comment]
I just wanted to note here that I have a draft PR in the works for this (#473).  Folks are welcome to push updates to that PR directly.

**Comment by nespinoza** [comment]
All right @bourque --- commited some extra docstrings directly to your repo (and thus PR).

**Comment by bourque** [comment]
The Groups & Integration docstrings will be taken care of in #453.

**Comment by nespinoza** [comment]
Moved to in-review for v.1.2 on the PR that @bourque opened: https://github.com/ExoCTK/exoctk/pull/473. After that's reviewed, I'll close this issue.
