### ISSUE TITLE
Explore using GitHub Actions or other CI solution instead of Travis

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#449]
Soon Travis will no longer be free (https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing), so unless we want to pay for it we will need to come up with a new CI solution.

**Comment by bourque** [comment]
Some existing examples:

- `Exo-Bespin`: https://github.com/exo-bespin/exo_bespin/blob/develop/.github/workflows/ci.yml
- `jwql`: https://github.com/mfixstsci/jwql/blob/add-github-actions/.github/workflows/python-package-conda.yml

**Comment by bourque** [comment]
@hover2pi @catherine-martlin @mfixstsci Should we try this?  Anyone have any concerns?

**Comment by hover2pi** [comment]
I recently implemented this for two of my other packages and it works like gangbusters. Let's do it.

**Comment by mfixstsci** [comment]
@hover2pi sounds good to me! Here is the most up-to-date version of the pipeline for JWQL. It will have some synergies with ExoCTK because we use multiple environment/os versions in our testing!

https://github.com/spacetelescope/jwql/blob/c6abe45d97ff576b0d5601b38d1c5f0eec331e40/.github/workflows/ci.yml

**Comment by catherine-martlin** [comment]
I think we can add the actions results to the PR using the info here: https://docs.github.com/en/actions/reference/events-that-trigger-workflows

I think we just need to add Pull Request as an event trigger.

**Comment by nespinoza** [comment]
Hi everyone --- this is done, right? I think we can close this issue. @bourque; @mfixstsci?

**Comment by mfixstsci** [comment]
Hey @nespinoza it is still an open PR

https://github.com/ExoCTK/exoctk/pull/476

**Comment by bourque** [comment]
This is solved via #476
