### ISSUE TITLE
environment-xx.yml issues with Pip and Asteval

### ISSUE THREAD

**Issue by Witchblade101** [ExoCTK/exoctk#455]
(base) zor:env dlong$ conda env create -f environment-3.7.yml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

I added "- pip=20.2.4" to environment-3.7.yml

"setup.py install" fails with an error:

error: asteval 0.9.13 is installed but asteval>=0.9.16 is required by {'lmfit'}
(although I see there is an open issue to remove lmfit)

Fixed by changing "- asteval==0.9.13" to "- asteval==0.9.16"

Some warnings, but no more errors.

I checked for the same problems in environment-3.6.yml:

(base) zor:env dlong$ conda env create -f environment-3.6.yml
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

Made same changes for pip and asteval as in environment-3.7.yml.

**Comment by catherine-martlin** [comment]
Hello! Thank you so much for submitting your input - I'm going to sort this so we are sure to take a look at our next team meeting (later this month). We should have an update on a timeline to address it then.

**Comment by bourque** [comment]
@Witchblade101 Thanks for creating this issue and apologies for taking so long on it.  This should now be fixed with the merge of #468 and so it will be available in the `develop` branch immediately and will be fixed in `master` in our next release (~end of March).  In the meantime, let me know if you run into any further issues!
