### ISSUE TITLE
performance regression in `contam_visibility.visibilityPA.using_gtvt`

### ISSUE THREAD

**Issue by falkben** [ExoCTK/exoctk#460]
We have noticed a performance regression in more recent versions of exoctk in the `contam_visibility.visibilityPA.using_gtvt` function (used by exo-mast).

Here's a summary of my findings:

```
Name (time in s)   Min       Max       Mean     StdDev   Median     IQR   Outliers  OPS      Rounds   Iterations
-----------------------------------------------------------------------------------------------------------------------
develop (py38)     1.0909    1.2363    1.1308   0.0604   1.1036    0.0579   1;0     0.8843   5        3
develop (py36)     1.0345    1.0621    1.0476   0.0115   1.0438    0.0188   2;0     0.9546   5        3
master (py38)      1.0745    1.2483    1.1147   0.0751   1.0823    0.0565   1;1     0.8971   5        3
master (py36)      1.0260    1.0499    1.0359   0.0107   1.0333    0.0193   1;0     0.9653   5        3
0.4.0 tag (py38)   0.6111    0.6397    0.6204   0.0120   0.6119    0.0182   1;0     1.6126   5        3
0.4.0 tag (py36)   0.6066    0.6654    0.6231   0.0240   0.6128    0.0197   1;1     1.6047   5        3
-----------------------------------------------------------------------------------------------------------------------
```

In order to reproduce:

I used [pytest-benchmark](https://pypi.org/project/pytest-benchmark/). I created a separate conda environment for python 3.6 and 3.8. I did not do a fresh install in the environments for each branch, so they share the same dependencies within each environment.  However, I do not see differences between environments, only between branches, so I don't think this is the cause of the performance difference.

This is my test file:

```python
from exoctk.contam_visibility import visibilityPA

def call_using_gtvt():
    instrument = 'NIRISS'
    ra = "-66"
    dec = "44"
    return visibilityPA.using_gtvt(ra, dec, instrument)

def test_benchmark_call_using_gtvt(benchmark):
    benchmark.pedantic(call_using_gtvt, iterations=3, rounds=5)
```

I benchmarked this after finding that exo-mast targetvis plots were taking around 500 ms longer... so this seems to correspond.

Was this already known? py-spy may be helpful here if we don't know what's causing the slow down.

Thanks for any additional information.

**Comment by falkben** [comment]
Edited the description above to provide more benchmark results across different commits and environments.

**Comment by falkben** [comment]
I suspect the slowdown might be related to this section of code: https://github.com/ExoCTK/exoctk/blob/master/exoctk/contam_visibility/visibilityPA.py#L388-L401

if this is necessary, perhaps there's a way to vectorize it to avoid the for loops

added in [this](https://github.com/ExoCTK/exoctk/commit/26b537b1544ac5482f45d00c0800cd394b2df1f0) commit

**Comment by nespinoza** [comment]
Hi @falkben,

 Thanks a ton for this comprehensive report! We'll put it in the agenda for our next ExoCTK team meeting (Jan 19th), and will get back to this issue to see how we can handle it!
 
 N.

**Comment by catherine-martlin** [comment]
(Sorry! I hit the wrong button while reviewing your great input!)

**Comment by falkben** [comment]
It looks like there's a lot of opportunity to vectorize the operations inside the `using_gtvt` function. My PR, linked above, addresses the section of code that is filtering badPAs against paNomnan but there's likely other areas to do as well. My testing indicates that vectorizing the code speeds things up by about 200ms, so that doesn't fully recover the performance difference reported in this ticket

**Comment by falkben** [comment]
the results from the same benchmark, on develop branch, with my patch above applied, for comparison with this issue. Note, milliseconds instead of seconds.

```
Name (time in ms)                       Min       Max      Mean   StdDev    Median      IQR  Outliers     OPS  Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------
test_benchmark_call_using_gtvt     689.7068  720.1474  701.7793  15.5694  691.0521  27.7793       2;0  1.4249       5           3
```

**Comment by falkben** [comment]
Hi, Just checking in to see if there's been any opportunity to take a look at this? Thanks!

**Comment by nespinoza** [comment]
Hi @falkben,

 Sorry for the very slow response on this. You caught us on the middle of defining our issue prioritization process within ExoCTK :-). I'll have a chat with @jaymedina and @hover2pi who are the tool champions to get into this ASAP. 

 Thanks!
Néstor
