### ISSUE TITLE
Add support and environment files for Python v3.8 and v3.9

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#464]
Currently only Python v3.6 and v3.7 are supported. Add `yaml` files to `env` directory and new tests to Travis.

**Comment by falkben** [comment]
Awesome! Would also be nice to have updated versions on pypi.org supporting these Python versions: https://pypi.org/project/exoctk/

**Comment by bourque** [comment]
I'm currently working on a PR for this (#469), but while testing things out I noticed that our Travis builds are using python 3.8, even in the 3.6, 3.7, and 3.9 env builds. 😱 I'll work on fixing that.

**Comment by bourque** [comment]
Python 3.8 and 3.9 are now supported with the merge of #469!

@falkben I also pushed the latest ExoCTK release (v1.1) to PyPI, and it appears to `pip install` successfully in the new environments.  But let me know if you run into any issues with that.
