### ISSUE TITLE
Installation issues when installing from setup.py on python 3.8

### ISSUE THREAD

**Issue by falkben** [ExoCTK/exoctk#465]
Following up after my conv. w/ @hover2pi and @jaymedina and related to https://github.com/ExoCTK/exoctk/issues/387

When installing exoctk into a fresh conda environment from setup.py I noticed a few minor issues, hopefully can be fixed up by: https://github.com/ExoCTK/exoctk/issues/464

Here are the two issues I noticed:

- setup.py does not specify a version of astropy, so it installs the latest. However, I've found that the `jwst_gtvt` package pinned in the setup.py file conflicts with newer versions of astropy. The last working version of astropy w/ `jwst_gtvt` is 4.0.4. Solution might be to update jwst_gtvt (no idea if newer versions work with newer versions of astropy) or pinning astropy to `<4.1`. Ideally `jwst_gtvt` would indicate which version of astropy it worked with so then the dependency resolver would take care of the rest...
- `jwst_gtvt` doesn't get installed automatically unless it's put into the `install_requires` section of the setup.py.  This I believe was a change to pip in version 19.0: https://pip.pypa.io/en/stable/news/#id449 you can add it to the requires section directly now:
`'jwst_gtvt @ git+https://github.com/spacetelescope/jwst_gtvt.git@cd6bc76f66f478eafbcc71834d3e735c73e03ed5'`

Really happy I don't have to create the data directories or env. variables anymore, thanks!

**Comment by bourque** [comment]
@falkben With the merge of #469 there is now a python 3.8 environment that uses `astropy<4.1`.  I also adopted your fix to remove the need for `dependency_links`, thanks for that suggestion!

The changes are now in the `develop` branch, and will be part of `master` upon our next release (end of march). 

Let me know if you run into any further issues!
