### ISSUE TITLE
Swtich 'master' branch to 'main' 

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#481]
GitHub is moving to switching the name of the default branch from `master` to `main`, so we should do the same!

**Comment by nespinoza** [comment]
Working on this!

**Comment by mfixstsci** [comment]
Looks like it's been updated! Users with a cloned copy should do the following:

```
git branch -m master main
git fetch origin
git branch -u main main
git remote set-head origin -a
```
