### ISSUE TITLE
Error bands on LDC tool do not reflect covariance between coefficients

### ISSUE THREAD

**Issue by nespinoza** [ExoCTK/exoctk#487]
Hi all,

 As per discussion in today's meeting, the on-line LDC tool "error bands" show the errors via bootstrap considering samples of the errors on the coefficients:

![Screen Shot 2021-04-13 at 5 56 30 PM](https://user-images.githubusercontent.com/2046682/114626362-9b96d600-9c81-11eb-9e61-22497d32d1e8.png)

 However, this doesn't account for the covariance between coefficients, which is the reason why the error bands look so wide. The [covariance is already been calculated by `curve_fit` in the limb-darkening tool](https://github.com/ExoCTK/exoctk/blob/b3ad5d0716a299befb10b3bd3b74490028b14983/exoctk/limb_darkening/limb_darkening_fit.py#L306), in fact, so it should be a matter of propagating that to the [bootstraping function](https://github.com/ExoCTK/exoctk/blob/b3ad5d0716a299befb10b3bd3b74490028b14983/exoctk/limb_darkening/limb_darkening_fit.py#L163) used to plot the error bands: instead of sampling random coefficients from a [normal distribution](https://github.com/ExoCTK/exoctk/blob/b3ad5d0716a299befb10b3bd3b74490028b14983/exoctk/limb_darkening/limb_darkening_fit.py#L188), a [multi-variate normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.multivariate_normal.html) could be used using that covariance. 
 
  I'll get to this when I find some time, but we need to decide if this covariance matrix is something we might want to report as well!

Néstor

**Comment by hover2pi** [comment]
Resolved in #577
