### ISSUE TITLE
Extend test coverage for Tier 2 Software Standards

### ISSUE THREAD

**Issue by bourque** [ExoCTK/exoctk#504]
As part of the [Tier 2 Software Standards for INS JWST Community Tools](https://github.com/spacetelescope/ins-jwst-community-software/blob/master/tier2_standards/test_coverage.md), the `exoctk` package needs sufficient tests that "test the major functionality of the code".  We should identify and address and areas of the code that need additional test coverage in order to conform to this standard.

**Comment by bourque** [comment]
@nespinoza @hover2pi @catherine-martlin @mfixstsci Hi All, as mentioned in our meeting, please take some time to think about the ExoCTK tool(s) you are familiar with and if there are any areas that are missing unit test coverage.  If you have any ideas, please describe them in this ticket.  Thanks!

**Comment by mfixstsci** [comment]
@bourque would we want to extend any of these out to the web app? I could write some tests for the target resolver and some of the MAST tools we use.

**Comment by bourque** [comment]
> @bourque would we want to extend any of these out to the web app? I could write some tests for the target resolver and some of the MAST tools we use.

@mfixstsci Yeah, that would be great!  The more coverage we have, the better.
