### ISSUE TITLE
Update date range for contamination visibility plots

### ISSUE THREAD

**Issue by chamblee-st** [ExoCTK/exoctk#568]
To assist with observation planning the range of dates on the horizontal axis of contamination visibility plots should be more up to date. Currently the end date is January 2024. 

One could hard code the date range from now to several years in the future or, even better, make it based on the system date from now until several years in the future.

Based on conversation with Joe, it seems that this UI change depends on on updates to ephemeris data (jwst_gtvt).

**Comment by hover2pi** [comment]
Resolved in #577
