### ISSUE TITLE
Dates not properly formatted on hover of contamination visibility plot

### ISSUE THREAD

**Issue by chamblee-st** [ExoCTK/exoctk#569]
When user hovers over contamination visibility plot dates are currently displaying as long strings of numbers followed by a '%', as shown in the attached screen grab.
![ExoCTK hover](https://github.com/ExoCTK/exoctk/assets/57812804/32a44ec4-289c-4b4b-a9fa-1f1734efd6d3)

This only occurs in Exo.MAST, for example: https://exo.mast.stsci.edu/exomast_planet.html?planet=WD1856534b click on JWST Visibility.

**Comment by hover2pi** [comment]
Resolved in #577
