### ISSUE TITLE
Epoch of source coordinates in Contamination Tool

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#581]
The contam tool doesn't specify the epoch the contaminant sources' coordinates. Since they are pulled from Gaia EDR3, they are actually 2016 coordinates. Be sure to display this information to the user. Should we use J2000 coordinates instead?

**Comment by JeffValenti** [comment]
I think you are asking if we should we use (FK5, Equinox=J2000) at epoch J2000 or ICRS at epoch=2016.0. Gaia DR3 provides the latter. Vizier I/355/gaiadr3 calculates the former as a convenience, for example. See:

- https://www.cosmos.esa.int/web/gaia/faqs#ICRSICRF
- https://en.wikipedia.org/wiki/International_Celestial_Reference_System_and_its_realizations
- https://docs.astropy.org/en/stable/api/astropy.coordinates.ICRS.html

Assuming astropy.coordinates handles ICRS, I would vote for that. Embrace the future.

**Comment by hover2pi** [comment]
Added in #590
