### ISSUE TITLE
Legend error with LightCurve

### ISSUE THREAD

**Issue by Icoti** [ExoCTK/exoctk#583]
Here is an information about a bug regarding a legend error reported on Bokeh Discourse:
https://discourse.bokeh.org/t/got-keyerror-legend/11100
The legend argument has to be updated.

**Comment by hover2pi** [comment]
Thanks! I'll fix the updated kwarg and include it in the next release.

**Comment by hover2pi** [comment]
Lightcurve fitting removed in #590
