### ISSUE TITLE
Add galaxy support to contam tool

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#594]
The Contamination and Overlap tool only shows contamination from stars currently. The reason is that we don't have an order 0 trace for an arbitrary galaxy to simulate. However, they pop up in observations (e.g. WASP-63b) without warning.

If we don't want to dive directly into modeling galaxy contaminants, just update the contam tool to draw a big dashed circle on the detector simulation where a galaxy order 0 is predicted to appear. This would have the relative brightness and other metadata from Gaia available on hover, like the star order 0s.

Not sure what to do about dispersed galaxy traces though. Could just use the stellar traces but they are scaled based on an estimate of the effective temperature of the star given its NIR colors. OK to use this estimate for a galaxy @nespinoza ? The correct thing to do would be to make a similar library of galaxy SEDs but then we get into galaxy classification issues as well.

**Comment by nespinoza** [comment]
I agree with using stellar traces for now, although would be good to indicate with a special flag in the contam overlap itself. We can upgrade them later once we understand the dispersed trace of galaxies in the tool.

**Comment by hover2pi** [comment]
Added in #597
