### ISSUE TITLE
Bokeh spectra plots are cut

### ISSUE THREAD

**Issue by gbruno88** [ExoCTK/ExoCTK#62]
Found with exotransmit:
If the spectral features extend over the plot limits, when unzooming the features are actually cut. The same if the spectrum is downloaded.
![screen shot 2018-03-16 at 1 39 00 pm](https://user-images.githubusercontent.com/24527823/37536130-1b648022-2920-11e8-85a8-870304c66cdb.png)

**Comment by hover2pi** [comment]
Moving this to `ExoCTKWeb`
