### ISSUE TITLE
Printing LDC results

### ISSUE THREAD

**Issue by gbruno88** [ExoCTK/ExoCTK#64]
For a large number of channels, the results are printed up to a maximum number of rows, with a "..." in between for the missing ones (both on the website and in the downloaded table).
<img width="1200" alt="screen shot 2018-04-24 at 6 39 07 pm" src="https://user-images.githubusercontent.com/24527823/39239066-2ae68778-4880-11e8-889b-c66b1dfa8ba7.png">

**Comment by hover2pi** [comment]
Moving this to `ExoCTKWeb` since it's a web site issue.
