### ISSUE TITLE
Create Wiki Page about Installation 

### ISSUE THREAD

**Issue by catherine-martlin** [ExoCTK/exoctk#65]
Step one is for me to be able to successfully install both ExtoCTK and ExoCTKWeb. Step two is to create the wiki that will guide others after me.

**Comment by catherine-martlin** [comment]
This [page](https://github.com/ExoCTK/ExoCTK/wiki/Current-Steps-to-get-ExoCTK-Running) is now created - it will likely need semi-often checks and updates as our codebase changes and the dependencies change with it.

**Comment by catherine-martlin** [comment]
For now, we will be waiting on our planned updates to the ExoCTK codebase (PEP, templates for packages, etc.) before updating what is currently at the Wiki page.

**Comment by jaymedina** [comment]
Some comments/suggestions/questions on the June 2018 version of the Wiki article, after installing ExoCTK:

> Good idea on suggesting to create a new conda environment
> Should members of the project also run the ExoCTK setup.py with `develop` rather than `install`? 
> I believe adding the `DYLD_` and `LD_` paths to my .bashrc prevented some of my executables from running, since conda uses @rpath to manage libraries. 
> I had to regress to SciPy vers. 0.17.0 for it to work after installing ExoCTK. Need to look into this issue further. 
> My environment required `msgpack` to be installed before installing `idlsave`

Thanks

**Comment by jaymedina** [comment]
Update on last bullet: 
Just saw that `idlsave` is being imported through `scipy` as `from spicy.io import readsav`, so we no longer need to pip install `idlsave`

**Comment by jaymedina** [comment]
Suggestion to add:
* pip install `lmfit` 

After this I was able to import `ExoCTK` with no errors

**Comment by bourque** [comment]
I think we can close this now that we have proper install instructions in the `README` (#200) and a `conda` environment (#188)
