### ISSUE TITLE
All WFC3 channels produce same coefficients

### ISSUE THREAD

**Issue by gbruno88** [ExoCTK/ExoCTK#72]
Calculating coefficients for a Teff = 6789, log g = 4.149, [Fe/H] = 0.0 star in the WFC3 band.
Both PHOENIX and ATLAS models give same result for every channel (quadratic LD law). It seems the models produce always the same points for the LD law to fit.
![figure_1](https://user-images.githubusercontent.com/24527823/41780060-ad44daf4-7601-11e8-8244-d34d3b0ca1a9.png)

**Comment by hover2pi** [comment]
Having trouble reproducing this. I think it's fixed (e0e14be). If you try it again and have the same problem, send me the code!
