### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#74]
The README is horribly out of date. Rewrite it with all current sub packages, descriptions and plots.

**Comment by hover2pi** [comment]
I was thinking we should revamp this while we're working on it, especially since as the number of sub packages grows, this README will get unwieldy.

First of all, we need install instructions.

Then perhaps a short summary of each sub package with no images but a link to the sub package README, which has more detail, references, maybe an example, and nice plots.

What do you think @ExoCTK/development

**Comment by kevin218** [comment]
@hover2pi This plan sounds reasonable.

**Comment by hover2pi** [comment]
Ok, @catherine-martlin and I are going to meet about it tomorrow to plan our assault.

**Comment by catherine-martlin** [comment]
AT DAWN WE RIDE, @hover2pi . (JK, more like 3pm.)

**Comment by julesfowler** [comment]
Feel free to pull me in if you want my help!

**Comment by catherine-martlin** [comment]
This README will be our master version of documentation which we will use to wrangle the website and the Read the Docs. First steps will be to remove the initialisms; provide more details in projects that are done/further along; also update the general info (see website for example). 

@julesfowler and @hover2pi - I will want to meet with you both to go over the modules and update our documentation on these.

**Comment by catherine-martlin** [comment]
This is dealt with by #83 . Closing this now since it's under there.
