### ISSUE TITLE
Make ONE environment variable for data, not SEVEN!

### ISSUE THREAD

**Issue by hover2pi** [ExoCTK/exoctk#81]
Our data is scattered across a bunch of directories for some reason. I propose we consolidate and require a singe env var to be created at installation `exoctk_data`.

**Comment by catherine-martlin** [comment]
There is the question of how to best get this data to the user, too. Having one tree of data is agreed upon, but perhaps to allow only specific branches of the data downloadable. Some possible ideas (we discussed reasons, but these are just general notes as we're not ready to make a full decision): (1) store it in the git repo; (2) have the data hosted at the exoctk website and provide the user instructions on what/where to get it and/or codes to check what data you have and what is available; (3) have the data be conda or pip installable, etc.

**Comment by hover2pi** [comment]
@julesfowler suggested putting all the data in a zip file available for the user to download via the Website, a la `jref` and `pandeia.engine` data. This seems the simplest and is battle tested by other ST tools. Then we can just make the one environment variable that points to the unzipped dir.

Any reasons NOT to do it this way?

**Comment by hover2pi** [comment]
Done in #173
