### ISSUE TITLE
Update All Documentation

### ISSUE THREAD

**Issue by julesfowler** [ExoCTK/exoctk#83]
Our `sphinx` documentation is literally years old at this point.
If someone can revitalize the structure it would be fairly simple to then have each person change their packages. 
- [x] Have people the README.rst with their most up-to-date information: 
     - [x]  `contam-visibility`
     - [x]  `integration_groups`
     - [x]  `limb_darkening`
     - [x]  `lightcurve_fitting`
    ~~`nircam_coronagraphy`~~
- [x] Update Index Page to properly reflect the actual subpackages
     - [x]  `contam-visibility`
     - [x]  `integration_groups`
     - [x]  `limb_darkening`
     - [x]  `lightcurve_fitting`
     ~~`nircam_coronagraphy`~~
- [x] Check the subpackage automatic sphinx results online
~~Update the structures/documentation if the html created by sphinx is wrong~~
- [x] Update the workflow
- [x] Create a documentation workflow

**Comment by catherine-martlin** [comment]
This is the same as issue #66 I think!

**Comment by catherine-martlin** [comment]
See https://github.com/ExoCTK/exoctk/wiki/Documentation-and-Tutorial-Workflow-Plan and https://github.com/ExoCTK/exoctk/wiki/Workflow
