### ISSUE TITLE
APT Phase Constraint Overlap Tool (Time Series Observations)

### ISSUE THREAD

**Issue by julesfowler** [ExoCTK/exoctk#84]
Create an observation planning tool to calculate phase overlap.

@kevin218 holds the secrets...

**Comment by kevin218** [comment]
I hereby reveal my secrets... to calculating the phase constraints on transit observations.  Including eclipses will make this only slightly more complicated.  The goal is to automatically pull these numbers from exoplanets.org.

# WASP-17b
period  = 3.7354845     # Days
t0      = 2454592.80154 # BJD or HJD
obsdur  = 34447.38/3600 # Hours
winSize = 1.0           # Hours

minphase= 1.0 - ((obsdur+winSize)/2./24/period)
maxphase= 1.0 - ((obsdur-winSize)/2./24/period)
print(minphase, maxphase)

**Comment by catherine-martlin** [comment]
Question, @kevin218 or @julesfowler do we already pull information from exoplanets.org in any other scripts? Is there already a structure for how we're doing that or should I look into the best method to do that query or scrap or whatever it ends up needing to be?

**Comment by julesfowler** [comment]
There's definitely a tool for this that soooomeone wrote?

**Comment by kevin218** [comment]
I would start with asking Peter Forshay.  He went to Penn State recently to update exoplanets.org, so he should know.

**Comment by hover2pi** [comment]
Correct me if i'm wrong but I think @exowanderer has a standalone script but it's not incorporated into ExoCTK because @hrwakeford is working on a similar (and better supported) script via ExoMAST, which we plan to use for all our exoplanet needs.

**Comment by julesfowler** [comment]
ExoMAST is what I was thinking of.

**Comment by catherine-martlin** [comment]
Awesome, I will look into that when I start needing that step for this tool. Just wanted to be sure I didn't re-invent a wheel we already had.

**Comment by kevin218** [comment]
Two options to look into eventually:
https://github.com/pforshay/exoplanets_org_work
https://github.com/bmorris3/exoparams

**Comment by catherine-martlin** [comment]
Would be nice to use exomast api or something like that where you can enter the name of the planet and it will auto-populate the fields that we need for this. (This might be a good extension with Mees.)

**Comment by catherine-martlin** [comment]
@kevin218 - do we have preferences on what we want to call this tool? Also, any preferences on where it should end up for the webpage - i.e. under another header such as observation planning?

**Comment by kevin218** [comment]
Start Window.

It should go with the other observation planning tools.



Sent from my Verizon, Samsung Galaxy smartphone


-------- Original message --------

**Comment by catherine-martlin** [comment]
See #158 for current progress.
