### ISSUE TITLE
Generic Grid model interface.

### ISSUE THREAD

**Issue by julesfowler** [ExoCTK/exoctk#86]
The General Grid can take a small piece of the Goyal Grid and re-normalize them to a given set of parameters. 

@hrwakeford and I have the data on the reduced grid, and Hannah also knows also knows the specifics of what parameters are fixed vs normalized vs ...

Her code to do this is already written and available here : https://github.com/hrwakeford/Generic_Grid

**Comment by hover2pi** [comment]
Done in #173
