### ISSUE TITLE
Where in the exo-world is exo-transmit.

### ISSUE THREAD

**Issue by julesfowler** [ExoCTK/ExoCTK#88]
Exotransmit is a lovely and useful tool. However -- it exists right now as a `python` wrapper to a powerful `C` library.

Right now (or about to be right now) we have ripped our exotransmit bc it is crashing our installations and making our Travis CI fail. 

However -- we need to work this back in somehow. 

The question is how do we want to do this. Potentially there are a few options : 
1. We should speed test it -- perhaps exotransmit could be thoughtfully rewritten in `python` and not take a million years? 
2. Perhaps `Cython` could be the answer -- after I get more familiar with it working on the TLC models, I might be able to write a `Cython` version that would be easier to include. 
3. We can wrap it again -- but do it better so everything doesn't crash.

**Comment by hover2pi** [comment]
See you in hell, exotransmit.
