### ISSUE TITLE
Forward Modeling Landing Page

### ISSUE THREAD

**Issue by kevin218** [ExoCTK/ExoCTK#93]
The website needs a landing page for the forward modeling module describing each code, the physical parameters that can be varied, and the limits of those parameters.

**Comment by catherine-martlin** [comment]
Should this issue be opened on the ExoCTKWeb repository? https://github.com/ExoCTK/ExoCTKWeb/issues

**Comment by kevin218** [comment]
Right!  I'll close this one and move it.
